using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using SharpOSC;

namespace App
{
    public partial class Form1 : Form
    {
        protected string DireccionIp { get; set; } = "192.168.0.1";
        protected bool VisualizarIp { get; set; } = true;

        protected Previsualizador previsualizador { get; set; } = Previsualizador.Create();
        protected List<Video> Videos = new List<Video> {
            new Video{ Name = "Track 1", Number = 1, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description= "Ningún hombre tiene una memoria lo suficientemente buena para ser un mentiroso exitoso. – Abraham Lincoln" },
            new Video{ Name = "Track 2", Number = 2, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description= "Cada strike me acerca más al siguiente home run. – Babe Ruth" },
            new Video{ Name = "Track 3", Number = 3, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description= "Todos nuestros sueños se pueden hacer realidad si tenemos el coraje de perseguirlos. – Walt Disney." },
            new Video{ Name = "Track 4", Number = 4, Picture = Application.StartupPath+"\\Images\\anime.jpg", Description= "La valentía no siempre ruge. A veces, es la vocecita al final del día que dice: mañana lo volveré a intentar.  – Mary Anne Radmacher" },
            new Video{ Name = "Track 5", Number = 5, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description= "Un viaje se mide mejor en amigos que en millas. –  Tim Cahill" },
            new Video{ Name = "Track 6", Number = 6, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description= "Si piensas que la aventura es peligrosa, prueba la rutina. Es mortal.- Pablo Coelho" },
            new Video{ Name = "Track 7", Number = 7, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description= "El gran placer de la vida es hacer lo que la gente dice que no puedes.  – Walter Bagehot" },
            new Video{ Name = "Track 8", Number = 8, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description= "El éxito es caer siete veces y levantarte ocho. –  Proverbio japonés" },
            new Video{ Name = "Track 9", Number = 9, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description= "Un viajero sin capacidad de observación es como un pájaro sin alas. – Moslih Eddin Saadi" },
            new Video{ Name = "Track 10", Number = 10, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 11", Number = 11, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 12", Number = 12, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 13", Number = 13, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 14", Number = 14, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 15", Number = 15, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 16", Number = 16, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 17", Number = 17, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 18", Number = 18, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 19", Number = 19, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 20", Number = 20, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 21", Number = 21, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 22", Number = 22, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 23", Number = 23, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 24", Number = 24, Picture = Application.StartupPath+"\\Images\\motos-3.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 25", Number = 25, Picture = Application.StartupPath+"\\Images\\motos-1.jpg", Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
            new Video{ Name = "Track 26", Number = 26, Picture = Application.StartupPath+"\\Images\\motos-2.jpg", Description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet sem justo. Suspendisse euismod est quis lectus feugiat malesuada. Suspendisse feugiat, est sit amet venenatis aliquet, tellus ex consectetur magna, eu auctor enim libero blandit neque. Aliquam molestie justo leo, tristique viverra purus pretium vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt massa nec magna lacinia, in commodo dolor molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer eros velit, egestas non leo eu, scelerisque volutpat erat. In vitae enim purus. Sed nulla odio, rutrum eleifend vehicula id, laoreet in orci. Sed purus mauris, convallis egestas dolor in, malesuada fringilla justo. Curabitur id pretium velit. Curabitur id mauris libero. Nulla facilisi.\r\n Morbi ac ante ultricies, pulvinar est ut, maximus nulla. Nulla commodo molestie enim vitae dapibus. Sed imperdiet, lectus ac pellentesque faucibus, ex magna suscipit est, eu tincidunt lacus erat et odio. Quisque metus purus, finibus a elit sed, consequat cursus metus. Maecenas commodo arcu eget arcu pellentesque, gravida ornare nibh consequat. Vestibulum sollicitudin mollis ligula, nec auctor velit convallis in. Aenean eget eleifend lorem. Maecenas vitae nunc velit. Suspendisse ac nisl lacus." },
        };

        public Form1()
        {
            InitializeComponent();
            labelContent.Text = "";
            labelDireccionIp.Visible = this.VisualizarIp;
            textBox1.Visible = this.VisualizarIp;
            textBox1.Text = this.DireccionIp;
            previsualizador.onVideoChanged += (Object sender, Video video) =>
            {
                Console.WriteLine(video != null ? video.Name : "Null");
            };
            int pages = (this.Videos.Count / 6) + 1;
            this.tableLayout.RowCount = pages;
            this.Videos.ForEach((Video video) =>
            {
                Button button = new Button();
                button.Text = video.Name;
                button.Click += (s,e) =>
                {
                    Console.WriteLine($"Click on {video.Number}");
                    this.sendMessage(video.Number);
                    this.pictureBox1.BackgroundImage = Image.FromFile(video.Picture);
                    labelContent.Text = video.Description;
                };
                this.tableLayout.Controls.Add(button);
            });
        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            this.DireccionIp = (sender as TextBox).Text;
        }

        private void sendMessage(int number)
        {
            var message = new SharpOSC.OscMessage("/mxw/set", (number) + 1, 42.01f, "hello world");
            var sender = new SharpOSC.UDPSender("192.168.0.8", 7000);
            sender.Send(message);
        }
    }
}
